sources:
  - name: ktzh_gwr
    database: data
    schema: src
    tables:
      - name: ktzh_gwr_apartments
      - name: ktzh_gwr_houses
      - name: ktzh_gwr_entrance
  - name: ktzh_metadata
    database: data
    schema: src
    tables:
      - name: ktzh_ogd_metadata
      - name: ktzh_downloads_dataset

models:

  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_downloads_dataset
  # ---------------------------------------------------------------------------
    description: |
      Staging table for KTZH download statistics.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['datum', 'datensatz_id']
    columns:
      - name: datum
        tests:
          - dbt_expectations.expect_column_to_exist
  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gwr_geb
  # ---------------------------------------------------------------------------
    description: |
      Staging table for KTZH GWR.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['egid', 'stichtag']
    columns:
      - name: stichtag
        tests:
          - dbt_expectations.expect_column_to_exist
  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gwr_whg
  # ---------------------------------------------------------------------------
    description: |
      Staging table for KTZH GWR.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['stichtag', 'egid', 'ewid']
    columns:
      - name: stichtag
        tests:
          - dbt_expectations.expect_column_to_exist
  # ---------------------------------------------------------------------------
  - name: stgn_ktzh_gwr_ein
  # ---------------------------------------------------------------------------
    description: |
      Staging table for KTZH GWR.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: ['stichtag', 'egid', 'eged']
    columns:
      - name: stichtag
        tests:
          - dbt_expectations.expect_column_to_exist


